### ISSUE TITLE
Question about CLIP's zero-shot performance on the UCF101 dataset

### ISSUE THREAD

**Issue by jinyf123** [bryant1410/fitclip#1]
Hi, thanks for your great paper.
I have a question about CLIP's zero-shot performance on the UCF101 dataset. In Table 1b of this paper, the zero-shot top1 accuracy of CLIP in UCF101 is 74.5%, but according to Figure 3 of the [ActionCLIP](https://arxiv.org/pdf/2109.08472.pdf), the zero-shot accuracy of CLIP is near 70%.
Is there any difference in implementation?

**Comment by bryant1410** [comment]
Hey, I don't remember the details of ActionCLIP, but here are some potential differences that come to my mind:
* We reported only the split 1 on UCF101, I think the same as CLIP did.
* The frame sampling strategy. We take 4 frames uniformly.
* The text prompting. We use text prompts, the same ones as CLIP.

I think a 5% top-1 accuracy difference is reasonable if the evaluation protocol is not exactly the same.

**Comment by jinyf123** [comment]
thanks a lot
